HOST = 'IP ADDRESS OF THE SERVER THIS IS RUNNING ON'
UDP_IP = 'IP ADDRESS OF WIFI LINK'
UDP_PORT = 9760
START = '180'
END = '|\0'
COMMANDS = {"on":1, "resume":1, "off":0}
SONOS = 'IP ADDRESS OF SONOS PLAYER'
